# generated by rig/desc_fit.py - word-index edits over the OFFICIAL text the user
# extracts; keyed by the Japanese source hash; result hash guards against drift.
CONDENSE_GENERATED = {
    'f50af3537f1be0ef': {  # bank 395 str 19
        'ops': [['del', 5, 7]],
        'want': '20417c1818743e1d',
    },
    'f18be837e6f259de': {  # bank 395 str 24
        'ops': [['sub', 12, 14, ['at.']]],
        'want': 'a4a1c8faeabeabce',
    },
    'f00fd2b728f9c798': {  # bank 395 str 25
        'ops': [['sub', 5, 9, ['watching']], ['sub', 11, 12, ['suspect', 'throughout.']]],
        'want': 'b7efd55360561143',
    },
    'f0615d16fb19db80': {  # bank 395 str 29
        'ops': [['sub', 0, 3, ['Colorful']], ['del', 4, 5], ['sub', 10, 12, ['is']]],
        'want': '55320414150eea62',
    },
    '7978451eb529ed7d': {  # bank 395 str 32
        'ops': [['sub', 8, 15, ['this', 'room.', 'What', 'are']], ['del', 16, 17]],
        'want': '68eae50d828fabb1',
    },
    '2a2b3348378b89c9': {  # bank 395 str 33
        'ops': [['del', 9, 11], ['del', 14, 15]],
        'want': '8b5a245b34eaa464',
    },
    'b9bfffe6e21c78c4': {  # bank 395 str 44
        'ops': [['sub', 0, 6, ["Azea's", 'food.', 'In']], ['sub', 13, 16, ['show;']], ['del', 17, 19]],
        'want': '3e81c563af9ee569',
    },
    'c9940e5a1cf87764': {  # bank 395 str 55
        'ops': [['sub', 0, 5, ['The', 'candy', "castle's", 'rock', 'crystals', 'have']], ['del', 6, 7], ['sub', 9, 20, ['bottom,', 'for', 'some', 'reason.']]],
        'want': 'f7a4273ab25b7fbd',
    },
    '4ca09c37128b8236': {  # bank 395 str 82
        'ops': [['sub', 1, 4, ["tea's"]], ['sub', 6, 9, ['comes', 'from']], ['sub', 12, 13, ['than']], ['sub', 14, 15, ["morning's."]]],
        'want': '66d7e24249e10410',
    },
    'ec6949b2d96c77dd': {  # bank 395 str 90
        'ops': [['del', 2, 4], ['del', 5, 6], ['sub', 13, 15, ['it?']]],
        'want': 'f4f405144142c3ad',
    },
    'c5ae616adf65b39f': {  # bank 395 str 97
        'ops': [['sub', 11, 15, ['came']]],
        'want': '3c8d43c6ac330d57',
    },
    '9a6fc65b7a97b631': {  # bank 395 str 99
        'ops': [['del', 4, 5], ['del', 7, 13], ['sub', 14, 15, ["raincoat's", 'shoulder.']], ['sub', 19, 23, ['spot']]],
        'want': '7a3234fc50b1dce2',
    },
    '4b644814062d95e8': {  # bank 395 str 105
        'ops': [['sub', 0, 2, ['Entered']], ['del', 4, 7], ['sub', 9, 12, ['roof', 'one', 'at', 'a', 'time,', 'and']], ['del', 13, 17], ['sub', 18, 24, ['same', 'way.']]],
        'want': '487a1fbd965c6c36',
    },
    '987aff7ee87079b0': {  # bank 395 str 107
        'ops': [['ins', 5, ['departing']], ['del', 7, 10]],
        'want': '3f9c33101a9d87f7',
    },
    'c9637726e19bce57': {  # bank 395 str 114
        'ops': [['sub', 1, 4, ['by']], ['sub', 6, 11, ['Should', 'have', 'been']], ['ins', 13, ['trailer']], ['sub', 14, 26, ['yesterday,']], ['sub', 27, 28, ['usual.']]],
        'want': '96daef0f0f154086',
    },
    'de3f509d3c09e811': {  # bank 395 str 123
        'ops': [['sub', 0, 2, ['The']], ['sub', 7, 13, ['put']], ['del', 15, 16]],
        'want': '49fd09685b329984',
    },
    '559e8e853a508bc0': {  # bank 395 str 124
        'ops': [['del', 0, 2], ['ins', 5, ['was', 'found']], ['sub', 6, 12, ['Most', 'likely']]],
        'want': '19f5b6047e7a08f1',
    },
    'a4cec7ab17380879': {  # bank 395 str 125
        'ops': [['del', 9, 10]],
        'want': 'f824f4a4fbd19527',
    },
    '890690e16002a507': {  # bank 395 str 128
        'ops': [['sub', 2, 4, ['ran', 'along']], ['sub', 8, 11, ['building,', 'with']], ['sub', 14, 16, ['per']]],
        'want': '0f634aa245082f21',
    },
    '3a201bfa11bac48d': {  # bank 432 str 5
        'ops': [['sub', 0, 3, ['Bullet']], ['del', 5, 6]],
        'want': 'd5063900a72396fd',
    },
    '77d1fd2cd07567c3': {  # bank 432 str 10
        'ops': [['del', 6, 8]],
        'want': '9aa06c249bd5e3a8',
    },
    '9730695c842e497e': {  # bank 432 str 12
        'ops': [['sub', 13, 17, ['Laser']]],
        'want': '6eb65449858aee70',
    },
    '24ea24f426730732': {  # bank 432 str 24
        'ops': [['sub', 8, 9, ['as']], ['sub', 10, 13, ['escaped.']], ['del', 16, 17]],
        'want': '2aaf16cbd8cde9e2',
    },
    '109a59bc9e985119': {  # bank 432 str 38
        'ops': [['del', 7, 8], ['del', 10, 11]],
        'want': 'e5c353c09d92b558',
    },
    '2027833639eaa047': {  # bank 432 str 40
        'ops': [['sub', 5, 9, ['when']], ['sub', 10, 12, ['wore', 'it', 'to', 'administer']], ['sub', 14, 16, ['mudpack.']]],
        'want': 'a2bdf7610911050b',
    },
    'fc50a26a5a48575c': {  # bank 432 str 43
        'ops': [['sub', 0, 1, ['Doors']], ['sub', 2, 6, ['for', 'a', 'detected']], ['del', 7, 9], ['del', 10, 11], ['sub', 13, 14, ['sounds', 'for']], ['sub', 16, 19, ['bracelet.']], ['sub', 20, 24, ["can't"]], ['del', 25, 26]],
        'want': 'ee1ff508143c4fdb',
    },
    'b30e7c2b32d0e798': {  # bank 432 str 45
        'ops': [['sub', 0, 2, ['Folding']], ['sub', 8, 14, ["Knight's;"]]],
        'want': 'db02d1214f453dfb',
    },
    '3e03a0b1efac2e00': {  # bank 432 str 54
        'ops': [['sub', 0, 3, ['Signs']], ['del', 15, 16]],
        'want': 'c90ce9fd15fddd5b',
    },
    '688643427fe082c0': {  # bank 432 str 55
        'ops': [['sub', 0, 3, ['Signs']], ['sub', 16, 18, ['is']]],
        'want': '43eaaf28e3197d25',
    },
    '87e413095df1d365': {  # bank 432 str 57
        'ops': [['del', 12, 14]],
        'want': '47cf8b9c12cf1c79',
    },
    'cf985ec3c20bd60c': {  # bank 432 str 58
        'ops': [['del', 5, 6], ['sub', 13, 16, ['Detects']]],
        'want': '6e6934688a06d9a7',
    },
    '23dc287b23fa8e26': {  # bank 432 str 64
        'ops': [['sub', 0, 6, ['Interim', 'report:']], ['sub', 15, 18, ['neck', 'from']]],
        'want': '11efee4b8e5c48df',
    },
    'ad75bfec566f3de8': {  # bank 432 str 73
        'ops': [['sub', 4, 9, ['exist:', 'one', 'on']], ['sub', 12, 15, ['one', 'on']], ['del', 17, 19], ['sub', 20, 24, ['at']]],
        'want': '36b3275f39282ff1',
    },
    '8c75c7a3c97ea693': {  # bank 432 str 74
        'ops': [['sub', 15, 17, ['Not']], ['del', 18, 20]],
        'want': '0b730000f79b21f3',
    },
    'e7cc51f9453147f6': {  # bank 432 str 75
        'ops': [['sub', 8, 9, ['murder']], ['del', 12, 13], ['sub', 17, 20, ['on', 'Carcerato.']]],
        'want': '3ff6694ee054828c',
    },
    '05aec82a2e02a0a1': {  # bank 432 str 76
        'ops': [['sub', 0, 4, ['Used']], ['sub', 11, 12, ['pulleys']], ['sub', 14, 17, ['ropes']]],
        'want': '0841c50447f0cab5',
    },
    '57fa53afbafd4e8e': {  # bank 432 str 78
        'ops': [['sub', 0, 2, ['In']], ['sub', 4, 6, ['room']]],
        'want': 'e092bbe110beedb0',
    },
    '7742e17a7a4a618d': {  # bank 432 str 112
        'ops': [['sub', 13, 17, ['had']]],
        'want': '0dc7feac138af08c',
    },
    '27b1a09d96543a37': {  # bank 432 str 127
        'ops': [['sub', 1, 5, ['instantly', 'developing', 'photos.']], ['del', 7, 8], ['sub', 11, 15, ['exposures;']], ['sub', 17, 18, ['remain.']]],
        'want': '560c7bbdda293fd3',
    },
    '08e242e197590bcd': {  # bank 432 str 165
        'ops': [['del', 2, 5], ['sub', 6, 8, ['flower,']]],
        'want': '5a485f23745e7114',
    },
    '9f43a01670a0f158': {  # bank 432 str 169
        'ops': [['del', 14, 15]],
        'want': 'b48702efcc49abc9',
    },
    '9ba43025ad7911e4': {  # bank 432 str 171
        'ops': [['sub', 6, 8, ['be']]],
        'want': 'b4a1f4399a6c757c',
    },
    '27b6ba8f62e32634': {  # bank 432 str 175
        'ops': [['sub', 1, 6, ['resulted', 'from']], ['sub', 18, 19, ['were']]],
        'want': '9584e3afe0e0b1dd',
    },
    '031d90f5a6d8bf86': {  # bank 432 str 179
        'ops': [['sub', 9, 10, ['flower']], ['sub', 16, 20, ['unknown.']]],
        'want': 'fda59813ac395080',
    },
    '198dfcc41f096620': {  # bank 432 str 180
        'ops': [['sub', 0, 3, ['Ringleader:']], ['del', 7, 8], ['sub', 9, 10, ['flower']], ['del', 11, 12], ['sub', 13, 16, ['A', 'facial']], ['sub', 17, 18, ['showed', 'past']], ['sub', 19, 27, ['mask.']]],
        'want': 'eb61d0c5c7002178',
    },
    'a53e19a2f97b364b': {  # bank 432 str 184
        'ops': [['sub', 0, 6, ['Its', 'recorder']]],
        'want': 'b45e5ccd2fd670b9',
    },
    'ce2da5e211b0d6d5': {  # bank 432 str 202
        'ops': [['sub', 2, 5, ['concrete', 'shards.']], ['sub', 9, 11, ['on', 'the']]],
        'want': 'fa0e9a2c82e7dcd1',
    },
    '72c4509800c5a3c5': {  # bank 432 str 209
        'ops': [['sub', 3, 7, ['original', 'Taurusaurus.']], ['del', 8, 9], ['sub', 11, 12, ['off']], ['del', 13, 17], ['ins', 19, ['roof']]],
        'want': 'bb0e187ead703ed5',
    },
    '9957b1cfceca8c13': {  # bank 432 str 212
        'ops': [['del', 1, 2], ['sub', 5, 6, ['Gavelle']], ['sub', 9, 16, ['roof.', 'No']], ['sub', 23, 26, ['down.']]],
        'want': '2384f8947c56da7d',
    },
    '76ca66853a185138': {  # bank 432 str 229
        'ops': [['sub', 1, 4, ['case:']], ['sub', 7, 9, ['kidnapped,']], ['del', 12, 13]],
        'want': 'de535dbee50e2cb1',
    },
    '76ca66853a185138': {  # bank 432 str 230
        'ops': [['sub', 1, 4, ['case:']], ['sub', 7, 9, ['kidnapped,']], ['del', 12, 13]],
        'want': 'de535dbee50e2cb1',
    },
    '76ca66853a185138': {  # bank 432 str 231
        'ops': [['sub', 1, 4, ['case:']], ['sub', 7, 9, ['kidnapped,']], ['del', 12, 13]],
        'want': 'de535dbee50e2cb1',
    },
    '428ad699431d6e6f': {  # bank 432 str 240
        'ops': [['sub', 0, 3, ['Drawn']], ['sub', 10, 11, ['in']], ['sub', 16, 18, ['Shows']], ['sub', 21, 26, ['that', 'night.']]],
        'want': 'bef21b4b1e47b3b5',
    },
    '8137752655337e8d': {  # bank 432 str 243
        'ops': [['sub', 16, 18, ['pass.']]],
        'want': '2ddf99db4ad072ce',
    },
    'f7c20d7e741a91f4': {  # bank 432 str 246
        'ops': [['sub', 4, 6, ['promotion.']], ['del', 17, 20]],
        'want': 'f85fc1ea61984166',
    },
    'f7c20d7e741a91f4': {  # bank 432 str 247
        'ops': [['sub', 4, 6, ['promotion.']], ['del', 17, 20]],
        'want': 'f85fc1ea61984166',
    },
    '85e837b7a7131301': {  # bank 432 str 256
        'ops': [['sub', 5, 7, ['precinct,']], ['sub', 12, 13, ['of']], ['sub', 14, 16, ['murder.']]],
        'want': 'c1b8a9b5c8cc1056',
    },
    'cb7e6f6abc0a94f4': {  # bank 432 str 257
        'ops': [['sub', 0, 2, ['Self-styled']], ['sub', 5, 11, ['second', 'Yatagarasu,', 'out']], ['sub', 12, 13, ['steal']], ['sub', 14, 21, ['truth', 'itself.']]],
        'want': 'dad8ab130ff7f797',
    },
    '8a0d1ac4ab5ee37d': {  # bank 432 str 259
        'ops': [['del', 0, 2], ['sub', 6, 11, ['Targeted', 'during']], ['del', 12, 17], ['sub', 19, 25, ['the', 'welcome', 'event.']]],
        'want': 'a57605a00305022a',
    },
    '16b74b029cd18069': {  # bank 432 str 260
        'ops': [['sub', 0, 4, ["President's"]], ['sub', 5, 6, ['second-in-command.']], ['del', 9, 11], ['sub', 12, 19, ['firearms', 'specialist.']]],
        'want': '7dab8c0bf921b6bc',
    },
    'd788c1e0926c870a': {  # bank 432 str 261
        'ops': [['sub', 4, 14, ['security.', "Can't"]], ['del', 17, 19]],
        'want': '166c992884817c10',
    },
    '0ce0a61854821c0a': {  # bank 432 str 262
        'ops': [['sub', 2, 7, ['Led']], ['sub', 9, 16, ['security.', 'Died']], ['sub', 20, 21, ['duty,', 'it', 'seems.']]],
        'want': 'f831429121711011',
    },
    'c6737e70747ad605': {  # bank 432 str 263
        'ops': [['sub', 3, 5, ['seller,']], ['del', 10, 11]],
        'want': 'b97b99c93d1e9ef0',
    },
    '6d07b3fb63e341e6': {  # bank 432 str 265
        'ops': [['sub', 0, 7, ['Pro', 'assassin.', 'Attacked']], ['sub', 11, 12, ['ago;']], ['sub', 13, 20, ['wounded']]],
        'want': 'a35b1ac7b4710e98',
    },
    '781930b32c142cc8': {  # bank 432 str 267
        'ops': [['sub', 2, 5, ['Killed']], ['sub', 6, 8, ['held']], ['sub', 11, 18, ['center.', 'Body', 'found']]],
        'want': 'e6d7dd16883c1907',
    },
    '2299ecc38fafa883': {  # bank 432 str 268
        'ops': [['sub', 3, 8, ["I've"]], ['sub', 9, 12, ['known,', 'not']], ['sub', 15, 17, ['Apparently']], ['sub', 18, 22, ['abroad.']]],
        'want': '70a9c5efc737732f',
    },
    'eb4e98140aa98485': {  # bank 432 str 269
        'ops': [['sub', 6, 10, ['once']], ['sub', 11, 14, ["father's", 'aide.']]],
        'want': '761586220f97535d',
    },
    '40d941ec94730e30': {  # bank 432 str 270
        'ops': [['del', 5, 7]],
        'want': '9ef12afa5c8bf020',
    },
    'd63a89aaf0bc6e29': {  # bank 432 str 271
        'ops': [['sub', 0, 8, ['Former', 'boxer.', 'Escaped', 'via']], ['ins', 9, ['cell']], ['sub', 13, 24, ['center.', 'Pet']]],
        'want': '4e1f3a6bb3598794',
    },
    '6ef1013881196b1b': {  # bank 432 str 272
        'ops': [['sub', 0, 3, ['District']], ['del', 5, 8], ['sub', 9, 14, ['member;']]],
        'want': '96342e614fd311d1',
    },
    '26fa55168ca9b21b': {  # bank 432 str 276
        'ops': [['sub', 0, 2, ['An']], ['sub', 7, 8, ['found']], ['sub', 9, 15, ['body', 'first,']], ['sub', 19, 22, ['doubts...']]],
        'want': 'a90006c201b2ab80',
    },
    '890e82ffd6ea17d8': {  # bank 432 str 277
        'ops': [['del', 1, 2], ['sub', 8, 10, ['Training']]],
        'want': '03ce5769a2294c92',
    },
    'bcd309e2f4d20d6c': {  # bank 432 str 278
        'ops': [['sub', 0, 3, ['Trainee']], ['sub', 4, 6, ['stylist;']], ['sub', 7, 8, ['to', 'find']]],
        'want': '513c3bd8c18a7206',
    },
    'f550fe4669bb8111': {  # bank 432 str 281
        'ops': [['sub', 0, 4, ['Prison', 'warden.']], ['del', 11, 13]],
        'want': '704ac4f917e88075',
    },
    '308964d2b25e8bae': {  # bank 432 str 282
        'ops': [['sub', 0, 7, ['Blind', 'ex-assassin.', 'Tools:']], ['sub', 13, 17, ['Small']], ['sub', 18, 23, ['heralded', 'him.']]],
        'want': '08b15526a711bd26',
    },
    '3d36657422b51421': {  # bank 432 str 284
        'ops': [['del', 5, 8]],
        'want': '4ae20136a72ba0fb',
    },
    '58565b323ac1e3cf': {  # bank 432 str 285
        'ops': [['sub', 5, 13, ['Co.', 'My', "father's", 'old', 'aide;']], ['del', 15, 16], ['sub', 17, 18, ['case.']]],
        'want': '12f649df01560008',
    },
    '71d8acf241fade1b': {  # bank 432 str 287
        'ops': [['sub', 0, 3, ['Found']], ['del', 4, 5], ['sub', 12, 21, ['Incident.', 'Now', 'in', 'prison.']]],
        'want': '3db5394b1682b546',
    },
    'c749ec83526339eb': {  # bank 432 str 291
        'ops': [['sub', 4, 6, ['Fond']]],
        'want': 'dc4fff65e64456dc',
    },
    '5a4f918df2376de7': {  # bank 432 str 292
        'ops': [['sub', 0, 10, ["Tangaroa's", 'former', 'assistant;', 'now', 'owns']], ['sub', 11, 16, ['Hall.', 'Loves']]],
        'want': 'ab530807196dc005',
    },
    'b24436b0fb6cc1cd': {  # bank 432 str 295
        'ops': [['sub', 0, 2, ['Confectioner']], ['sub', 5, 7, ['Known', 'back']], ['sub', 9, 13, ['U.K.', 'as']]],
        'want': 'a33a343d9138f3dc',
    },
    '7c641384c23ad78a': {  # bank 432 str 298
        'ops': [['sub', 0, 9, ['Confectioner']], ['sub', 14, 15, ['Wing', 'after', 'inhaling', 'poison', 'gas.']]],
        'want': '9cd1f8abea9e3320',
    },
    '1862466caaf6f94a': {  # bank 432 str 299
        'ops': [['sub', 7, 13, ['Said', 'to', 'have']], ['del', 18, 20]],
        'want': '2fa0d3d8da5bfc7d',
    },
    'bfa37cb8990021f1': {  # bank 432 str 300
        'ops': [['sub', 5, 10, ['childhood', 'friend.', 'Fancies']], ['del', 11, 14]],
        'want': '4b206210d2d425d7',
    },
    '3065c05874598da1': {  # bank 432 str 301
        'ops': [['sub', 0, 2, ['Greatest']], ['sub', 3, 13, ['ever,', 'by']], ['sub', 14, 16, ['own', 'account.', 'His', 'grasp', 'of']], ['sub', 18, 21, ['tenuous.']]],
        'want': '51530939c3ea048d',
    },
    'c19fecfeee156dab': {  # bank 432 str 304
        'ops': [['sub', 0, 2, ['Mysterious']], ['del', 5, 10], ['sub', 13, 15, ['Seems']], ['sub', 17, 20, ['amnesia,']]],
        'want': '6cbdffaf47a7fe5f',
    },
    'f0f2aee56ca120f9': {  # bank 432 str 305
        'ops': [['sub', 0, 2, ['Self-styled']], ['sub', 3, 10, ['Thief,', 'the', 'second', 'Yatagarasu.', 'Currently']]],
        'want': 'a1e9221ef70ca894',
    },
    '4d32035061c23721': {  # bank 432 str 306
        'ops': [['sub', 0, 2, ['Head']], ['sub', 5, 7, ['Performed']], ['ins', 8, ["victim's"]], ['sub', 9, 16, ['inspection.']]],
        'want': '82f63e5737e1393a',
    },
    'd4a1085864c88f16': {  # bank 432 str 307
        'ops': [['del', 4, 5], ['sub', 7, 12, ['Gifted']], ['sub', 13, 17, ['now']]],
        'want': 'f76e3b43d3f4f2cc',
    },
    'ee7fa00cf0ac21ce': {  # bank 432 str 308
        'ops': [['sub', 1, 8, ['victim.', 'A']], ['sub', 9, 12, ['attorney']], ['sub', 17, 18, ['Gavelle.']]],
        'want': '000ba378068cbbc2',
    },
    '581da7b6504182cd': {  # bank 432 str 309
        'ops': [['sub', 1, 5, ['victim.']], ['sub', 7, 14, ['attorney,', 'possibly']], ['ins', 15, ['secret']], ['del', 18, 19]],
        'want': '747bd0fb04b48079',
    },
    '6e0da30f405d9446': {  # bank 432 str 310
        'ops': [['sub', 0, 2, ['Committee', 'head,', 'ex-chief']], ['del', 3, 9], ['sub', 12, 21, ['Weepy.']]],
        'want': 'a7cd0d55efb74df8',
    },
    '232f5cd49e8a8494': {  # bank 432 str 311
        'ops': [['sub', 6, 8, ['Trying']]],
        'want': '60e6936989344158',
    },
    'c0771bc61b981a0d': {  # bank 432 str 313
        'ops': [['sub', 0, 2, ['Freelance']], ['del', 3, 4], ['sub', 6, 9, ['before.']], ['sub', 11, 15, ['sniffing']], ['sub', 16, 24, ['scoops.']]],
        'want': '0db45510eac1f78f',
    },
    'bdc940dcda78d0bd': {  # bank 432 str 314
        'ops': [['sub', 0, 2, ['Props']], ['sub', 5, 8, ['Studios;']], ['sub', 10, 11, ['find']], ['sub', 13, 16, ['Named']]],
        'want': 'd21b6cd6dba98ba8',
    },
    '3b6ac43aecbf4d9e': {  # bank 432 str 315
        'ops': [['sub', 0, 2, ['Child']], ['sub', 6, 9, ['movie.']], ['sub', 12, 13, ['age,']]],
        'want': 'b604df3b891d24a8',
    },
    '8faed6109d5bc6ed': {  # bank 432 str 316
        'ops': [['sub', 0, 2, ['Child']], ['sub', 6, 12, ['movie.']], ['sub', 14, 19, ['son', 'by']]],
        'want': '49a11b8a48a66841',
    },
    'b1196fd4ee592a7b': {  # bank 432 str 317
        'ops': [['sub', 0, 2, ['Judge']], ['del', 3, 7], ['sub', 8, 11, ['member.']], ['sub', 13, 15, ['involvement']]],
        'want': '6f1e47da78928bf0',
    },
    '5c51db711e6a8feb': {  # bank 432 str 318
        'ops': [['sub', 6, 8, ['Defends']], ['sub', 9, 11, ['Laguarde']], ['del', 12, 14], ['sub', 15, 16, ["Ringer's", 'stead.']]],
        'want': 'd436a09bdce147d9',
    },
    '0d8ed12115a2253e': {  # bank 432 str 319
        'ops': [['sub', 0, 6, ['Rookie', 'prosecutor,']], ['sub', 7, 11, ["'real", "winner'.", 'Fled']], ['sub', 12, 16, ['shock:']]],
        'want': 'f2dfbd8aacbaa22f',
    },
    '4884b7270ebf0605': {  # bank 432 str 322
        'ops': [['del', 0, 3], ['sub', 4, 11, ['Chairman;', 'ran']], ['sub', 14, 17, ['Now']]],
        'want': '2bf5a51fa2714dc0',
    },
    'e767b0e2590b9eba': {  # bank 432 str 323
        'ops': [['del', 7, 8]],
        'want': 'f5e61fb0a5cd6dcb',
    },
    '68f1900ab951b5df': {  # bank 432 str 324
        'ops': [['del', 0, 3], ['del', 11, 12]],
        'want': '2c95dec5a5f810aa',
    },
    'f51d60d5f92ede55': {  # bank 432 str 325
        'ops': [['sub', 0, 6, ['Blind', 'ex-assassin.', 'Escaped']], ['sub', 9, 11, ['ago;']], ['del', 12, 14]],
        'want': '695543d51d8cb098',
    },
    'ad156176ac3a5d24': {  # bank 432 str 327
        'ops': [['sub', 0, 2, ['Action']], ['sub', 6, 11, ['Playing']], ['del', 15, 17]],
        'want': '27710eddedc3ee5d',
    },
    'fced72aa7ec85af7': {  # bank 432 str 329
        'ops': [['sub', 0, 2, ['Trainee', 'animal', 'tamer']], ['sub', 6, 12, ['Circus.', 'The']], ['sub', 14, 19, ['it', 'all.']]],
        'want': '0043c5dfec38ff21',
    },
    'b8fb135c8245f6f5': {  # bank 432 str 331
        'ops': [['sub', 1, 5, ['victim.']], ['del', 6, 7], ['sub', 9, 10, ['killed', 'and', 'replaced']], ['sub', 12, 19, ['Wang']]],
        'want': '89d83f23e5ab2a12',
    },
    '19a4e1c45e58b922': {  # bank 432 str 334
        'ops': [['sub', 0, 5, ['Journalist']], ['del', 9, 10]],
        'want': '6369ff77d3f015ef',
    },
}
