# -*- coding: utf-8 -*-
"""Measure condensed descriptions against the DS box, and turn the ones that fit
into condense.py entries (word-index ops + result hash, no game text stored).

    python tools/desc_fit.py check     inventory/desc_overflow.json inventory/desc_condensed.json
    python tools/desc_fit.py emit      inventory/desc_overflow.json inventory/desc_condensed.json OUT_table.py
    python tools/desc_fit.py review    inventory/desc_overflow.json inventory/desc_condensed.json OUT_review.txt

desc_condensed.json: {"432:12": "condensed english", ...}. A value of "" means
"leave this row on the fan text" (documented decision).
"""
import sys, os, io, json, hashlib, difflib
PORT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.chdir(PORT)
import dstext, condense
from loc_patch import _to_units, _ds_plain, CTRL
from spt import all_strings


def wrap_lines(eng, suffix, age_text, px):
    old = dstext.LINE_PX; dstext.LINE_PX = px
    try:
        conv, _ = dstext.convert(_to_units(eng), page=False, hard_nl=False)
        if suffix:
            sc, _ = dstext.convert(_to_units(suffix), page=False, hard_nl=False)
            conv = conv + [0x0A] + sc
    finally:
        dstext.LINE_PX = old
    n_age = 1 if age_text else 0
    lines, cur = [], []
    for v in conv:
        if v == 0x0A: lines.append(cur); cur = []
        else: cur.append(v)
    lines.append(cur)
    widths = [sum(dstext._w(chr(v)) for v in l if not CTRL(v)) for l in lines]
    return n_age + len(lines), widths


def load(rows_path, cond_path):
    rows = json.load(io.open(rows_path, encoding='utf-8'))
    cond = json.load(io.open(cond_path, encoding='utf-8')) if os.path.exists(cond_path) else {}
    return rows, cond


def key(r): return '%d:%d' % (r['bank'], r['str'])


def check(rows, cond, verbose=True):
    fit, over, missing, skipped = [], [], [], []
    for r in rows:
        k = key(r)
        if k not in cond: missing.append(k); continue
        c = cond[k]
        if not c: skipped.append(k); continue
        n, widths = wrap_lines(c, r['suffix'], r['age'], r['px'])
        (fit if n <= r['allowed'] else over).append((k, n, r['allowed'], widths, c))
    if verbose:
        print('  fit: %d   over: %d   skipped(fan): %d   missing: %d' % (len(fit), len(over), len(skipped), len(missing)))
        for k, n, a, w, c in over:
            print('    OVER %-8s needs %d/%d  widths=%s\n         %s' % (k, n, a, w, c))
        if missing: print('  missing keys:', missing[:20], '...' if len(missing) > 20 else '')
    return fit, over, missing, skipped


def ops_for(official, condensed):
    """Word-index edit ops (condense.apply semantics: original indices, running offset)."""
    a = official.replace('\n', ' ').split(); b = condensed.split()
    sm = difflib.SequenceMatcher(a=a, b=b, autojunk=False)
    ops = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == 'equal': continue
        if tag == 'delete': ops.append(['del', i1, i2])
        elif tag == 'replace': ops.append(['sub', i1, i2, b[j1:j2]])
        elif tag == 'insert': ops.append(['ins', i1, b[j1:j2]])
    return ops


def apply_ops(official, ops):
    w = official.replace('\n', ' ').split(); off = 0
    for op in ops:
        if op[0] == 'del':
            a, b = op[1], op[2]; w[a + off:b + off] = []; off -= (b - a)
        elif op[0] == 'sub':
            a, b = op[1], op[2]; w[a + off:b + off] = op[3]; off += len(op[3]) - (b - a)
        else:
            a = op[1]; w[a + off:a + off] = op[2]; off += len(op[2])
    return ' '.join(w)


def emit(rows, cond, out_py):
    fit, over, missing, skipped = check(rows, cond, verbose=False)
    lines = ["# generated by rig/desc_fit.py - word-index edits over the OFFICIAL text the user",
             "# extracts; keyed by the Japanese source hash; result hash guards against drift.",
             "CONDENSE_GENERATED = {"]
    bad = 0
    for k, n, a, w, c in fit:
        r = next(x for x in rows if key(x) == k)
        ops = ops_for(r['official'], c)
        back = apply_ops(r['official'], ops)
        if back != c:
            bad += 1; print('  op round-trip mismatch for %s' % k); continue
        want = hashlib.sha1(back.encode('utf-8')).hexdigest()[:16]
        lines.append("    %r: {  # bank %d str %d" % (condense.key(r['ja_norm']), r['bank'], r['str']))
        lines.append("        'ops': %r," % (ops,))
        lines.append("        'want': %r," % want)
        lines.append("    },")
    lines.append("}")
    io.open(out_py, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('  wrote %s: %d entries (%d round-trip failures)' % (out_py, len(fit) - bad, bad))


def review(rows, cond, out_txt):
    with io.open(out_txt, 'w', encoding='utf-8', newline='\n') as f:
        f.write('CONDENSED EVIDENCE / LOGIC TEXT FOR REVIEW\n' + '=' * 78 + '\n')
        f.write('Each row: Japanese source, Capcom official (does not fit the DS box), the\n'
                'condensed version proposed to ship, and the fan translation that ships today.\n'
                'Question for the reviewer: does the condensed line lose or change anything a\n'
                'player could need to spot a contradiction? Length is already checked.\n\n')
        for r in rows:
            k = key(r); c = cond.get(k)
            f.write('[%s] %s box, %d lines\n' % (k, r['box'], r['allowed']))
            f.write('  JAPANESE : %s\n' % r['ja'])
            f.write('  CAPCOM   : %s\n' % r['official'])
            if c: f.write('  PROPOSED : %s\n' % c)
            elif c == '': f.write('  PROPOSED : (keep the fan text - see note)\n')
            else: f.write('  PROPOSED : (not yet written)\n')
            f.write('  FAN      : %s\n\n' % r['fan'])
    print('  wrote', out_txt)


if __name__ == '__main__':
    cmd = sys.argv[1]
    rows, cond = load(sys.argv[2], sys.argv[3])
    # normalised JA for hashing, as loc_patch does it
    for r in rows:
        r['ja_norm'] = _ds_plain([ord(c) for c in r['ja']])
    if cmd == 'check': check(rows, cond)
    elif cmd == 'emit': emit(rows, cond, sys.argv[4])
    elif cmd == 'review': review(rows, cond, sys.argv[4])
