# -*- coding: utf-8 -*-
"""Trim 28 testimony/rebuttal statements so each fits the DS engine's single
statement box (3 lines at the build's own width budget) instead of wrapping to
4 and being split 2+2 over two boxes - of which the engine only ever shows the
first (rig, entry 92 statement 2, 2026-09-22).

This table contains NO game text beyond a handful of GENERIC substitute words
(the same convention as tools/condense.py: "was", "prime", "which", and the
like - never a reconstructed sentence). Each row is keyed by (DS entry, string
index) and holds a short hash of the SOURCE - the Collection string's visible
text exactly as inject.py sees it at the hook point, right after
buttons.substitute() and before dstext.convert() - plus word-index edit
operations (deletions and substitutions, condense.py's op shape) and a `want`
hash of the resulting visible text. A Collection dump whose wording differs
from what these rows were built against fails the source hash and the string
is left untrimmed (see `apply`, below); the build log counts that as a
fallback rather than silently shipping a mismatched edit.

VISIBLE TEXT AND HASHING. `visible()` walks the raw pre-convert units the way
dstext.convert()'s own tokenizer does - arity-aware, so a control code's
argument units are never mistaken for text - and applies the SAME two
normalisations convert() applies before anything is wrapped: apostrophes
(ASCII "'" and the Collection's U+2019) fold to the ROM's own curly form
(dstext.APOS, U+201D) and a run of three or more periods folds to that many
copies of the ROM's ellipsis glyph (dstext.ELLIPSIS_UNIT, U+2025 - convert()
does this same fold on its OUTPUT stream after layout, on the fullwidth form;
here it is done on the plain codepoints before layout, which is equivalent
for a run that never straddles a wrap). This is what the private review
file's "original" and "final" fields already look like (read back from the
build / approved by the maintainer; the file is kept outside this repo), so
a row's `hash` and `want` are computed against exactly that text.

WORD OPS AND CONTROL CODES. Ops are condense.py's shape - ['del', a, b] drops
words [a, b) of the ORIGINAL word list (split on whitespace); ['sub', a, b,
[...]] replaces that range with the given words - but unlike condense.py
(which edits a plain string with no embedded codes: evidence descriptions
carry none at that stage) a statement string carries control codes
(emphasis spans, {E108} pauses, {E1D1} voice blips, ...) attached to
particular words, and those must never be dropped. `_slots()` walks the raw
units into one slot per whitespace-delimited word: each slot keeps the
control-code units seen since the previous separator and before its own first
character as its LEAD, and any seen after its own last character (up to the
next separator) as its TRAIL - in original relative order. There is no
separate prefix/suffix concept: codes before the very first word are that
word's LEAD and codes after the very last word are the last word's TRAIL, so
editing the first or last word carries them along like any other. Deleting a
range of slots concatenates that range's LEAD+TRAIL codes, in order, and
prepends them to the following kept slot's LEAD (or appends them to the
preceding kept slot's TRAIL, if the deletion runs to the end of the string);
substituting a range does the same concatenation and prepends it to the LEAD
of the range's first replacement word - UNLESS the range runs to the end of
the string, in which case the last deleted slot's TRAIL is the string's own
closing control sequence ({E102}/{E081}/... and whatever follows) and must
stay last, so the whole bundle is appended to the TRAIL of the last
replacement word instead (found the hard way: entry 265's sub() at the very
last word first put the box terminator in FRONT of "them."). This satisfies
the rule the spec states in one line: a code attached to a deleted word moves
to the neighbouring kept word and is never dropped, and a substituted word
keeps its codes. Words outside an edited range keep their characters and
codes; the separators between words are re-emitted as single spaces, and
apostrophes, quotes and ellipses are compared in normalised form. For the 28
statements in this table the result was verified unit for unit against the
approved text after conversion.
"""
import hashlib
import dstext

STMT_TRIM = {
    # Generated by a maintainer-side script (kept outside this repo) from a
    # private review file of approved wording; only the edit table lands here.
    # Row shape: (entry, string): {'hash': <source hash>, 'ops': [...], 'want': <result hash>}
    (9, 6): {'hash': '8878ec7a0877cbd7', 'ops': [['del', 6, 9]], 'want': 'de1c0a4a2c0d23d4'},
    (62, 5): {'hash': '0484855425f1b875', 'ops': [['del', 7, 10]], 'want': 'ceddcf2d0a9a9a7b'},
    (74, 9): {'hash': '12ac1030d1cd2d0e', 'ops': [['del', 2, 3]], 'want': '71932d274abacddf'},
    (92, 5): {'hash': 'd6b210f9dcd57155', 'ops': [['sub', 1, 5, ['while']]], 'want': '5dd5d64c4723b2bd'},
    (95, 5): {'hash': '1780b1e61d24e653', 'ops': [['del', 7, 10], ['del', 13, 14]], 'want': '4296d8cc9b7d5108'},
    (98, 4): {'hash': 'aefe392db95ccd54', 'ops': [['sub', 11, 14, ['plan.']]], 'want': 'f95bf6109d9c4671'},
    (127, 5): {'hash': '4657611f21169899', 'ops': [['sub', 15, 16, ['prime']]], 'want': 'cc54e41010b53e0d'},
    (134, 9): {'hash': '86177b071672bb73', 'ops': [['del', 7, 9]], 'want': '3ab657df9b70d746'},
    (148, 5): {'hash': '296db8ff8680e779', 'ops': [['sub', 12, 16, ['which']]], 'want': '2162b7bec73d6cb3'},
    (167, 5): {'hash': '0ce91aee817504d8', 'ops': [['del', 3, 6]], 'want': 'be4266210bf1d377'},
    (168, 4): {'hash': 'ab7f38e92dd2751b', 'ops': [['del', 14, 15]], 'want': 'bc14c42cc3bd69a0'},
    (182, 4): {'hash': 'cc8388ba617a1255', 'ops': [['del', 10, 11]], 'want': '6d6f96963a5af899'},
    (182, 7): {'hash': '211b114baf03bca2', 'ops': [['del', 7, 9]], 'want': 'd531d0711ef228ee'},
    (183, 7): {'hash': '73551130e2fdc80f',
               'ops': [['sub', 8, 10, ['making']], ['sub', 12, 14, ['serving']],
                       ['sub', 16, 18, ['everybody.']]],
               'want': '2d48fe79a0684d10'},
    (189, 9): {'hash': 'ebf466a52e55a349', 'ops': [['del', 4, 5], ['del', 13, 14]], 'want': 'ad2cb31bcf9b5ee4'},
    (193, 4): {'hash': 'f4300fc0227f5871', 'ops': [['del', 6, 7]], 'want': 'a57fc0b403ee09c7'},
    (219, 4): {'hash': '042e5ab0dd9e1b4a', 'ops': [['sub', 10, 12, ['else!']]], 'want': 'e93018823a9f3817'},
    (233, 7): {'hash': 'a2189a3bffae331d', 'ops': [['sub', 3, 4, ['this']], ['del', 5, 8]], 'want': 'c03bcf83c06ee0cc'},
    (235, 3): {'hash': '71dbe6b93673f374', 'ops': [['del', 4, 5], ['sub', 12, 13, ['real']]], 'want': 'dcaa1b0951c80e55'},
    (235, 5): {'hash': '63b87587db7de220', 'ops': [['sub', 0, 2, ['If']], ['sub', 5, 8, ['right,']]], 'want': '49e2a21ed260a0a1'},
    (235, 6): {'hash': 'c00ffa8286d96da1', 'ops': [['del', 5, 8]], 'want': 'ca665e75df617526'},
    (242, 6): {'hash': 'b2df3f8ad9e922be', 'ops': [['del', 7, 9]], 'want': 'c94975c9f72f221d'},
    (246, 3): {'hash': 'e2ef9cdac8464181', 'ops': [['del', 11, 12], ['del', 15, 16]], 'want': '7a50f4a7ef36ec7c'},
    (265, 5): {'hash': '918e1ca22cb8d20e', 'ops': [['sub', 17, 20, ['them.']]], 'want': '89db319214b709e3'},
    (302, 3): {'hash': '72365777e31dce77', 'ops': [['sub', 11, 16, ['my', 'kit.']]], 'want': '3c884e26bd9c60be'},
    (312, 7): {'hash': '35c6b891384a618c',
               'ops': [['sub', 11, 12, ['stage']], ['sub', 16, 20, ['everyone', 'off.']]],
               'want': 'e2d7f9b9371f7eb3'},
    (324, 4): {'hash': '4cb297e479f13845', 'ops': [['sub', 0, 2, ['Think']]], 'want': 'dccdc834842364d6'},
    (327, 3): {'hash': '8331e618dfe79eda', 'ops': [['del', 15, 17]], 'want': '5bb63bb8ea8eebce'},
}

_SEP = (0x20, 0x09, 0x0A, 0x00)


def _key(text):
    return hashlib.sha1(text.encode('utf-8')).hexdigest()[:16]


def _fold_ellipsis(chars):
    """Runs of 3+ ASCII/fullwidth periods fold to that many
    dstext.ELLIPSIS_UNIT - the same rule dstext.convert() applies to its
    output stream after layout, applied here to plain codepoints before
    layout (equivalent for a run that never straddles a wrap)."""
    out, i, n = [], 0, len(chars)
    while i < n:
        v = chars[i]
        if v in (0x2E, 0xFF0E):
            j = i
            while j < n and chars[j] in (0x2E, 0xFF0E):
                j += 1
            if j - i >= 3:
                out.extend([dstext.ELLIPSIS_UNIT] * (j - i))
            else:
                out.extend(chars[i:j])
            i = j
        else:
            out.append(v); i += 1
    return out


def _norm_char(v, state):
    """One character unit's normalised codepoint (apostrophe/quote only - the
    ellipsis fold is applied per-slot afterwards, in _slots). It keeps no
    open/close double-quote state: every straight quote maps to dstext.DQ_OPEN,
    which is only right because dstext uses the same glyph for opening and
    closing quotes (DQ_OPEN == DQ_CLOSE). `state` is passed through unchanged."""
    if v == 0x22:
        return dstext.DQ_OPEN, state
    if v in (0x27, 0x2019):
        return dstext.APOS, state
    return v, state


def _slots(units):
    """Split raw pre-convert units into a list of slots, one per
    whitespace-delimited word: {'lead': [unit-lists], 'chars': [codepoints],
    'trail': [unit-lists]}. LEAD holds control codes seen since the previous
    separator and before this word's first character (codes before the very
    first word land in slot 0's LEAD); TRAIL holds codes seen after this
    word's last character, up to the next separator (codes after the very
    last word land in the last slot's TRAIL). A slot's chars, decoded to a
    python str, is exactly one word of visible(units).split()."""
    slots, cur, pending, dq = [], None, [], False
    i, n = 0, len(units)
    while i < n:
        v = units[i]
        if dstext.CTRL(v):
            code = list(units[i:i + 1 + dstext.ARGS.get(v, dstext.DEFAULT_ARGS)])
            i += len(code)
            if cur is None:
                pending.append(code)
            else:
                cur['trail'].append(code)
            continue
        if v in _SEP:
            if cur is not None:
                slots.append(cur); cur = None
            i += 1
            continue
        if cur is None:
            cur = {'lead': pending, 'chars': [], 'trail': []}
            pending = []
        c, dq = _norm_char(v, dq)
        cur['chars'].append(c)
        i += 1
    if cur is not None:
        slots.append(cur)
    if pending:
        if slots:
            slots[-1]['trail'] += pending
        else:
            # no word at all in this string - not reachable by any of the
            # 28 rows; nothing sensible to attach the codes to.
            raise ValueError('stmt_trim: no words to attach control codes to')
    # fold each slot's own period run (never straddles a slot: the run is
    # inside one word's plain characters, e.g. a word with no space anywhere
    # near an embedded "......" - or is its own word between two spaces)
    for s in slots:
        s['chars'] = _fold_ellipsis(s['chars'])
    return slots


def _slot_word(s):
    return ''.join(chr(c) for c in s['chars'])


def visible(units):
    """Plain visible text of a raw (pre-convert) unit list, normalised the way
    dstext.convert() would present it once built: control codes are skipped,
    apostrophes fold to dstext.APOS, runs of 3+ periods fold to that many
    dstext.ELLIPSIS_UNIT, and any run of whitespace/NUL between words
    collapses to one space - the same soft-space treatment dstext.convert()
    gives a source newline not followed by {E20D} (dstext.py's `hard_nl`).
    Built from the SAME word split _slots()/apply() use, so a row's ops line
    up with visible(...).split() by construction. Matches
    private review file's "original"/"final" text exactly."""
    return ' '.join(_slot_word(s) for s in _slots(units))


def _apply_ops(slots, ops):
    """Apply condense.py-shaped ops to the slot list. Returns a new list."""
    slots = list(slots)
    off = 0
    for op in ops:
        if op[0] == 'del':
            a, b = op[1] + off, op[2] + off
            moved = []
            for s in slots[a:b]:
                moved += s['lead'] + s['trail']
            if b < len(slots):
                slots[b]['lead'] = moved + slots[b]['lead']
            elif a > 0:
                slots[a - 1]['trail'] = slots[a - 1]['trail'] + moved
            else:
                raise ValueError('stmt_trim: del would empty the string')
            del slots[a:b]
            off -= (b - a)
        elif op[0] == 'sub':
            a, b, words = op[1] + off, op[2] + off, op[3]
            moved = []
            for s in slots[a:b]:
                moved += s['lead'] + s['trail']
            new_slots = [{'lead': [], 'chars': _fold_ellipsis([ord(c) for c in w]), 'trail': []}
                         for w in words]
            # The moved bundle's last piece can be the STRING'S OWN closing
            # sequence (when b == len(slots), slots[b-1]['trail'] is whatever
            # follows the very last character of the string). That must stay
            # at the very end, not jump in front of the replacement words -
            # attach to the LAST new slot's TRAIL there; otherwise (a kept
            # word still follows) attach to the FIRST new slot's LEAD, next
            # to where the range used to start.
            if b < len(slots):
                new_slots[0]['lead'] = moved
            else:
                new_slots[-1]['trail'] = moved
            slots[a:b] = new_slots
            off += len(words) - (b - a)
        else:
            raise ValueError('stmt_trim: unknown op %r' % (op,))
    return slots


def _serialize(slots):
    out = []
    for k, s in enumerate(slots):
        for code in s['lead']:
            out += code
        out += s['chars']
        for code in s['trail']:
            out += code
        if k < len(slots) - 1:
            out.append(0x20)
    return out


def apply(entry, string_index, units):
    """Return (new_units, status). status is None when this (entry, string)
    has no row (units passed through unchanged, not counted); True when the
    row's source hash matched and the trim was applied; False when the source
    hash did not match (a different Collection dump) - units are left
    untouched and the caller counts a fallback."""
    row = STMT_TRIM.get((entry, string_index))
    if row is None:
        return units, None
    try:
        src = visible(units)
    except ValueError:
        return units, False
    if _key(src) != row['hash']:
        return units, False
    try:
        slots = _slots(units)
        slots = _apply_ops(slots, row['ops'])
        out = _serialize(slots)
    except ValueError:
        return units, False
    want = row['want']
    if want and _key(visible(out)) != want:
        return units, False
    return out, True
